# Auto-generated by cpcv_eval.py --watchlist  2026-06-09
# level: 'danger'=過学習/OOS損失  'warning'=要注意
CPCV_FLAGS = {
    "1975.T": {"level": "danger",  "pbo": 0.8,    "oos_pf": 1.75, "oos_wr": 61.5, "reason": "過学習 PBO 80.0%"},
    "7013.T": {"level": "danger",  "pbo": 0.667,  "oos_pf": 2.27, "oos_wr": 66.1, "reason": "過学習 PBO 66.7%"},
    "7172.T": {"level": "danger",  "pbo": 0.0,    "oos_pf": 0.95, "oos_wr": 45.3, "reason": "OOS PF 0.95 (損失) / OOS勝率 45.3%"},
    "8016.T": {"level": "danger",  "pbo": 0.733,  "oos_pf": 0.95, "oos_wr": 49.0, "reason": "過学習 PBO 73.3% / OOS PF 0.95 (損失)"},
    "8386.T": {"level": "danger",  "pbo": 0.8,    "oos_pf": 2.56, "oos_wr": 71.0, "reason": "過学習 PBO 80.0%"},
    "7181.T": {"level": "warning", "pbo": 0.4,    "oos_pf": 2.62, "oos_wr": 62.7, "reason": "要注意 PBO 40.0%"},
    "8061.T": {"level": "warning", "pbo": 0.467,  "oos_pf": 6.35, "oos_wr": 78.3, "reason": "要注意 PBO 46.7%"},
    "8091.T": {"level": "warning", "pbo": 0.0,    "oos_pf": 1.16, "oos_wr": 55.6, "reason": "OOS PF 1.16"},
    "8522.T": {"level": "warning", "pbo": 0.0,    "oos_pf": 1.04, "oos_wr": 50.0, "reason": "OOS PF 1.04"},
}
